import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-dvh bg-bg-primary">
      <header className="flex items-center justify-between px-6 py-4 border-b border-border-default">
        <div className="flex items-center gap-4">
          <Link href="/" className="w-8 h-8 rounded-lg bg-accent/10 border border-accent/20 flex items-center justify-center text-accent font-bold text-sm hover:bg-accent/20 transition-all">
            A
          </Link>
          <h1 className="text-base font-semibold text-text-primary">Terms of Service</h1>
        </div>
      </header>

      <div className="max-w-2xl mx-auto px-4 py-8 text-sm text-text-secondary leading-relaxed space-y-4">
        <p><strong className="text-text-primary">Last updated:</strong> June 2026</p>

        <h2 className="text-text-primary text-sm font-semibold mt-6">1. Acceptance</h2>
        <p>By using AXCIS ("the Service"), you agree to these terms. If you do not agree, do not use the Service.</p>

        <h2 className="text-text-primary text-sm font-semibold mt-6">2. Description</h2>
        <p>AXCIS is an AI-powered assistant designed to help startup founders with research, strategy, and execution. The Service provides conversational responses generated by a large language model. It is not a substitute for professional legal, financial, or business advice.</p>

        <h2 className="text-text-primary text-sm font-semibold mt-6">3. Use of Service</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>Use the Service only for lawful purposes</li>
          <li>Not attempt to reverse-engineer, abuse, or overload the underlying systems</li>
          <li>Not use the Service to generate harmful, illegal, or misleading content</li>
          <li>Not rely solely on AI-generated advice for critical business decisions</li>
        </ul>

        <h2 className="text-text-primary text-sm font-semibold mt-6">4. Intellectual Property</h2>
        <p>You retain all rights to your conversations and startup information. The Service itself, including its code and branding, is provided under an open-source license.</p>

        <h2 className="text-text-primary text-sm font-semibold mt-6">5. No Warranty</h2>
        <p>The Service is provided "as is" without any warranty. We do not guarantee that the AI responses are accurate, complete, or suitable for your specific situation. Always verify critical information independently.</p>

        <h2 className="text-text-primary text-sm font-semibold mt-6">6. Limitation of Liability</h2>
        <p>In no event shall the creators or maintainers of AXCIS be liable for any damages arising from your use of the Service, including but not limited to business decisions made based on AI-generated content.</p>

        <h2 className="text-text-primary text-sm font-semibold mt-6">7. Changes</h2>
        <p>We reserve the right to update these terms at any time. Continued use after changes constitutes acceptance of the new terms.</p>

        <h2 className="text-text-primary text-sm font-semibold mt-6">8. Contact</h2>
        <p>For questions about these terms, open an issue on the GitHub repository.</p>
      </div>
    </div>
  );
}
